# Generated by Django 4.1.7 on 2023-03-25 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_name_customuser_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
