# Generated by Django 4.1.7 on 2023-03-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthDate',
            new_name='Birth date',
        ),
    ]
