# Generated by Django 4.1.7 on 2023-03-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_birthdate_customuser_birth date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Birth date',
            new_name='birthDate',
        ),
    ]
