# Generated by Django 4.1.7 on 2023-04-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_name_remove_customuser_surname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('everyone', 'Fuck you'),)},
        ),
    ]
