# Generated by Django 4.1.7 on 2023-04-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('everyone', 'Can update'),)},
        ),
    ]
