# Generated by Django 4.1.7 on 2023-03-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(default='unnamed group', max_length=50)),
                ('groupSize', models.IntegerField(default=1)),
            ],
        ),
    ]
