# Generated by Django 4.1.7 on 2023-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='text',
        ),
        migrations.AddField(
            model_name='group',
            name='groupName',
            field=models.CharField(default='unnamed group', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='groupSize',
            field=models.IntegerField(default=1),
        ),
    ]
