# Generated by Django 4.1.7 on 2023-03-31 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New team', max_length=30)),
                ('teamLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdTeams', related_query_name='createdTeam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
