# Generated by Django 4.1.7 on 2023-03-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logedin', '0002_membership_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='New team', max_length=30, unique=True),
        ),
    ]
