# Generated by Django 4.1.7 on 2023-03-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logedin', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(default='Recently created team', max_length=60),
        ),
    ]
