# Generated by Django 4.1.7 on 2023-03-31 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logedin', '0004_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdTeams', related_query_name='createdTeam', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
