# Generated by Django 4.1.7 on 2023-04-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logedin', '0009_alter_team_teamleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
