# Generated by Django 4.1.7 on 2023-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logedin', '0011_rename_is_leader_membership_isleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
